import { describe, expect, it } from 'vitest';
import { AggregateTree } from '../src/model/tree';
import type { FolderRecord } from '../src/model/types';
import { createNodeFsProbe } from '../src/rules/probe';
import { discoverCaches } from '../src/rules/inventory/cache-discovery';
import type { RuleContext } from '../src/rules/types';
import type { RuleEnv } from '../src/rules/paths';
import type { InstalledApp, InstalledAppsSnapshot } from '../src/system/installed-apps';

const LOCAL = 'C:\\Users\\Ahmed\\AppData\\Local';
const ROAMING = 'C:\\Users\\Ahmed\\AppData\\Roaming';

const ENV: RuleEnv = {
  temp: `${LOCAL}\\Temp`,
  localAppData: LOCAL,
  appData: ROAMING,
  userProfile: 'C:\\Users\\Ahmed',
  windowsDir: 'C:\\Windows',
  programData: 'C:\\ProgramData',
};

const SPOTIFY: InstalledApp = {
  displayName: 'Spotify',
  publisher: 'Spotify AB',
  installLocation: '',
};

function folder(tree: AggregateTree, path: string, bytes = 0): void {
  const record: FolderRecord = {
    path,
    bytes,
    allocatedBytes: 0,
    fileCount: 0,
    folderCount: 0,
    linkCount: 0,
    newestMtimeMs: 0,
    errorCount: 0,
    partial: false,
  };
  tree.addFolder(record);
}

function context(tree: AggregateTree, installs?: InstalledAppsSnapshot): RuleContext {
  return { root: 'C:\\', tree, markers: [], probe: createNodeFsProbe(), installs };
}

function trusted(apps: InstalledApp[]): InstalledAppsSnapshot {
  return { apps, trusted: true };
}

describe('discoverCaches', () => {
  it('treats a GPU shader cache as a safe detected match regardless of installed apps', () => {
    const tree = new AggregateTree();
    folder(tree, `${LOCAL}\\NVIDIA\\DXCache`, 8400);
    const result = discoverCaches(context(tree, trusted([])), ENV);

    expect(result.findings).toEqual([]);
    expect(result.matches).toHaveLength(1);
    expect(result.matches[0]).toMatchObject({
      path: `${LOCAL}\\NVIDIA\\DXCache`,
      bytes: 8400,
      grade: 'safe',
      origin: 'detected',
    });
    expect(result.matches[0]!.recovery).toMatchObject({ reason: expect.stringContaining('regenerated by the driver') });
  });

  it('finds GPU caches under ProgramData and LocalLow with vendor-specific names', () => {
    const tree = new AggregateTree();
    folder(tree, 'C:\\ProgramData\\NVIDIA Corporation\\NV_Cache', 2200);
    folder(tree, 'C:\\Users\\Ahmed\\AppData\\LocalLow\\Intel\\ShaderCache', 512);
    folder(tree, `${LOCAL}\\AMD\\GLCache`, 1024);
    const result = discoverCaches(context(tree, trusted([])), ENV);

    expect(result.findings).toEqual([]);
    expect(result.matches.map((match) => match.path).sort()).toEqual(
      [
        'C:\\ProgramData\\NVIDIA Corporation\\NV_Cache',
        'C:\\Users\\Ahmed\\AppData\\LocalLow\\Intel\\ShaderCache',
        `${LOCAL}\\AMD\\GLCache`,
      ].sort(),
    );
  });

  it('labels a cache under an installed app as a display-safe finding, never a match', () => {
    const tree = new AggregateTree();
    folder(tree, `${LOCAL}\\Spotify\\Storage`, 6200);
    const result = discoverCaches(context(tree, trusted([SPOTIFY])), ENV);

    expect(result.matches).toEqual([]);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]).toMatchObject({
      path: `${LOCAL}\\Spotify\\Storage`,
      kind: 'app-matched',
      grade: 'safe',
      label: 'Spotify',
    });
  });

  it('labels a cache under a missing vendor as a review leftover finding', () => {
    const tree = new AggregateTree();
    folder(tree, `${LOCAL}\\Spotify\\Storage`, 6200);
    const result = discoverCaches(context(tree, trusted([])), ENV);

    expect(result.matches).toEqual([]);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]).toMatchObject({ kind: 'app-leftover', grade: 'review', label: 'Spotify' });
    expect(result.findings[0]!.reason).toContain('Leftover cache from Spotify');
  });

  it('labels a publisher-level match with the vendor instead of guessing the product', () => {
    const tree = new AggregateTree();
    folder(tree, `${LOCAL}\\Acme\\Cache`, 42);
    const result = discoverCaches(
      context(tree, trusted([{ displayName: 'Music Player', publisher: 'Acme Corporation', installLocation: '' }])),
      ENV,
    );

    expect(result.matches).toEqual([]);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]).toMatchObject({ kind: 'app-matched', grade: 'safe', label: 'Acme' });
    expect(result.findings[0]!.reason).toContain('installed app');
  });

  it('never produces actionable matches for app caches', () => {
    const tree = new AggregateTree();
    folder(tree, `${ROAMING}\\SomeApp\\Cache`, 100);
    folder(tree, `${LOCAL}\\Mystery\\Code Cache`, 100);
    const result = discoverCaches(context(tree, trusted([])), ENV);
    expect(result.matches).toEqual([]);
  });

  it('skips weak cache names when the registry is untrusted and degrades the rest to unrecognized', () => {
    const tree = new AggregateTree();
    folder(tree, `${LOCAL}\\Spotify\\Storage`, 10);
    folder(tree, `${LOCAL}\\Foo\\Cache`, 10);
    folder(tree, `${LOCAL}\\Cache`, 10);
    const result = discoverCaches(context(tree, { apps: [], trusted: false }), ENV);

    expect(result.matches).toEqual([]);
    expect(result.findings.map((finding) => finding.path).sort()).toEqual(
      [`${LOCAL}\\Cache`, `${LOCAL}\\Foo\\Cache`].sort(),
    );
    expect(result.findings.every((finding) => finding.kind === 'unrecognized')).toBe(true);
  });

  it('stops at the depth cap and still finds caches at the boundary', () => {
    const tree = new AggregateTree();
    folder(tree, `${LOCAL}\\A\\B\\C\\D\\Cache`, 10);
    folder(tree, `${LOCAL}\\A\\B\\C\\D\\E\\Cache`, 10);
    const result = discoverCaches(context(tree, trusted([])), ENV);
    expect(result.findings.map((finding) => finding.path)).toEqual([`${LOCAL}\\A\\B\\C\\D\\Cache`]);
  });

  it('suppresses paths owned by the curated registry rules', () => {
    const tree = new AggregateTree();
    folder(tree, `${LOCAL}\\Google\\Chrome\\User Data\\Default\\Code Cache`, 10);
    folder(tree, `${ROAMING}\\discord\\Cache`, 10);
    const result = discoverCaches(
      context(tree, trusted([{ displayName: 'Google Chrome', publisher: 'Google LLC', installLocation: '' }])),
      ENV,
    );
    expect(result.matches).toEqual([]);
    expect(result.findings).toEqual([]);
  });

  it('deduplicates candidates reachable from overlapping roots', () => {
    const tree = new AggregateTree();
    folder(tree, `${LOCAL}\\Temp\\Foo\\Cache`, 10);
    const result = discoverCaches(context(tree, trusted([])), ENV);
    expect(result.findings).toHaveLength(1);
  });

  it('ignores directories that do not look like caches', () => {
    const tree = new AggregateTree();
    folder(tree, `${LOCAL}\\Spotify\\Data`, 999);
    folder(tree, `${LOCAL}\\Spotify\\Logs`, 10);
    const result = discoverCaches(context(tree, trusted([SPOTIFY])), ENV);
    expect(result.findings).toEqual([]);
    expect(result.matches).toEqual([]);
  });
});
