export { AggregateTree } from './model/tree';
export type { TreeNode } from './model/tree';
export type { Entry, FolderRecord, Marker, NodeKind, ProgressUpdate } from './model/types';
export { NodeFsEnumerator } from './scanner/enumerator';
export type { Enumerator, ListResult } from './scanner/enumerator';
export { createExclusionPredicate } from './scanner/exclusions';
export type { ExclusionConfig } from './scanner/exclusions';
export { ScanSession } from './scanner/session';
export type { PoolOptions, ScanResult, SessionOptions } from './scanner/session';
export type { PoolLimits } from './scan/protocol';
export { defaultWorkerCount, DEFAULT_POOL_LIMITS } from './scan/limits';
export { scanTree } from './scanner/scanner';
export type { ScanConfig, ScanStats } from './scanner/scanner';
